SELECT DISTINCT
    CALL_DATE,
    DAYNAME(CALL_DATE) AS DAY_OF_WEEK,
    MONTH(CALL_DATE) AS MONTH_NUM,
    MONTHNAME(CALL_DATE) AS MONTH_NAME,
    QUARTER(CALL_DATE) AS QUARTER,
    YEAR(CALL_DATE) AS YEAR
FROM {{ ref('silver_veeva_calls') }}