USE DATABASE CDW_DEV_TEST;
CREATE OR REPLACE SCHEMA CDW_DEV_TEST.BRONZE;
CREATE OR REPLACE SCHEMA CDW_DEV_TEST.SILVER;
CREATE OR REPLACE SCHEMA CDW_DEV_TEST.GOLD;
CREATE OR REPLACE SCHEMA CDW_DEV_TEST.REFERENCE;

=======================================
//SEED
INSERT INTO CDW_DEV_TEST.BRONZE.RAW_VEEVA_CALLS VALUES
('VC-011','1234567890','2025-05-15','Virtual','Completed');

-- Check monitoring
SELECT * FROM CDW_DEV_TEST.REFERENCE.V_PIPELINE_MONITOR;

SELECT COUNT(*)  FROM CDW_DEV_TEST.BRONZE.RAW_VEEVA_CALLS;

SELECT COUNT(*)  FROM CDW_DEV_TEST.GOLD.FACT_CALL_ACTIVITY;

SELECT COUNT(*)  FROM CDW_DEV_TEST.SILVER.SILVER_VEEVA_CALLS


ALTER TASK CDW_DEV_TEST.PUBLIC.TASK_STAGING SUSPEND;




