-- CDW_TEST: ORCHESTRATION - STREAMS + TASK DAG
-- Purpose: Event-driven pipeline (runs only when new data arrives)
-- Author: MURALI
-- Created: 2026-05-02

CREATE OR REPLACE STREAM CDW_DEV_TEST.BRONZE.STM_RAW_VEEVA_CALLS
  ON TABLE CDW_DEV_TEST.BRONZE.RAW_VEEVA_CALLS;

CREATE OR REPLACE STREAM CDW_DEV_TEST.BRONZE.STM_RAW_HCP
  ON TABLE CDW_DEV_TEST.BRONZE.RAW_HCP;

CREATE OR REPLACE TASK CDW_DEV_TEST.PUBLIC.TASK_STAGING
  WAREHOUSE = 'COMPUTE_WH'
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('CDW_DEV_TEST.BRONZE.STM_RAW_VEEVA_CALLS')
    OR SYSTEM$STREAM_HAS_DATA('CDW_DEV_TEST.BRONZE.STM_RAW_HCP')
AS
  EXECUTE DBT PROJECT CDW_DEV_TEST.PUBLIC.DBT_020526 ARGS = 'run --select staging';

CREATE OR REPLACE TASK CDW_DEV_TEST.PUBLIC.TASK_SILVER
  WAREHOUSE = 'COMPUTE_WH'
  AFTER CDW_DEV_TEST.PUBLIC.TASK_STAGING
AS
  EXECUTE DBT PROJECT CDW_DEV_TEST.PUBLIC.DBT_020526 ARGS = 'run --select silver';

CREATE OR REPLACE TASK CDW_DEV_TEST.PUBLIC.TASK_GOLD
  WAREHOUSE = 'COMPUTE_WH'
  AFTER CDW_DEV_TEST.PUBLIC.TASK_SILVER
AS
  EXECUTE DBT PROJECT CDW_DEV_TEST.PUBLIC.DBT_020526 ARGS = 'run --select gold';

CREATE OR REPLACE TASK CDW_DEV_TEST.PUBLIC.TASK_CONSUME_STREAMS
  WAREHOUSE = 'COMPUTE_WH'
  AFTER CDW_DEV_TEST.PUBLIC.TASK_GOLD
AS
  BEGIN
    CREATE OR REPLACE TEMP TABLE CDW_DEV_TEST.PUBLIC.TEMP_CONSUME_1 AS 
      SELECT * FROM CDW_DEV_TEST.BRONZE.STM_RAW_VEEVA_CALLS;
    CREATE OR REPLACE TEMP TABLE CDW_DEV_TEST.PUBLIC.TEMP_CONSUME_2 AS 
      SELECT * FROM CDW_DEV_TEST.BRONZE.STM_RAW_HCP;
  END;

ALTER TASK CDW_DEV_TEST.PUBLIC.TASK_CONSUME_STREAMS RESUME;
ALTER TASK CDW_DEV_TEST.PUBLIC.TASK_GOLD RESUME;
ALTER TASK CDW_DEV_TEST.PUBLIC.TASK_SILVER RESUME;
ALTER TASK CDW_DEV_TEST.PUBLIC.TASK_STAGING RESUME;