CREATE OR REPLACE SCHEMA CDW_DEV_TEST.REFERENCE;

CREATE OR REPLACE VIEW CDW_DEV_TEST.REFERENCE.V_PIPELINE_MONITOR AS
SELECT
    NAME AS TASK_NAME,
    STATE AS TASK_STATE,
    SCHEDULED_TIME,
    COMPLETED_TIME,
    DATEDIFF('SECOND', SCHEDULED_TIME, COMPLETED_TIME) AS DURATION_SEC,
    RETURN_VALUE,
    ERROR_CODE,
    ERROR_MESSAGE
FROM TABLE(CDW_DEV_TEST.INFORMATION_SCHEMA.TASK_HISTORY(
    SCHEDULED_TIME_RANGE_START => DATEADD('DAY', -7, CURRENT_TIMESTAMP()),
    RESULT_LIMIT => 100
))
WHERE NAME IN ('TASK_STAGING', 'TASK_SILVER', 'TASK_GOLD', 'TASK_CONSUME_STREAMS')
ORDER BY SCHEDULED_TIME DESC;
=========================================================================================

-- Check pipeline history
SELECT * FROM CDW_TEST.REFERENCE.V_PIPELINE_MONITOR;

-- Check task status
SHOW TASKS IN CDW_TEST.PUBLIC;

-- Check stream status
SELECT SYSTEM$STREAM_HAS_DATA('CDW_TEST.BRONZE.STM_RAW_VEEVA_CALLS') AS VEEVA_HAS_DATA,
       SYSTEM$STREAM_HAS_DATA('CDW_TEST.BRONZE.STM_RAW_HCP') AS HCP_HAS_DATA;

-- Check row counts across layers
SELECT 'BRONZE - RAW_VEEVA_CALLS' AS LAYER, COUNT(*) AS ROWS FROM CDW_TEST.BRONZE.RAW_VEEVA_CALLS
UNION ALL SELECT 'BRONZE - RAW_HCP', COUNT(*) FROM CDW_TEST.BRONZE.RAW_HCP
UNION ALL SELECT 'SILVER - SILVER_VEEVA_CALLS', COUNT(*) FROM CDW_TEST.SILVER.SILVER_VEEVA_CALLS
UNION ALL SELECT 'GOLD - FACT_CALL_ACTIVITY', COUNT(*) FROM CDW_TEST.GOLD.FACT_CALL_ACTIVITY
UNION ALL SELECT 'GOLD - DIM_TIME', COUNT(*) FROM CDW_TEST.GOLD.DIM_TIME;

-- Recent query history
SELECT QUERY_ID, QUERY_TEXT, USER_NAME, START_TIME, EXECUTION_STATUS
FROM TABLE(CDW_TEST.INFORMATION_SCHEMA.QUERY_HISTORY(RESULT_LIMIT => 20))
ORDER BY START_TIME DESC;
